spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://47.104.92.214:3306/guns_test?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=CONVERT_TO_NULL&useSSL=false&serverTimezone=CTT
    username: root
    password: root
  redis:
    database: 0
    host: 192.168.159.10
    port: 6379
    password: 123456
  session:
    store-type: none
server:
  port: 8080
mybatis:
  mapperLocations: classpath:mapper/*.xml